### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by wernerbarnard** [saulmases/ant-design-sketch#1]
Hi,

I have a colleague trying to use the Ant Design files in Sketch, the english ones... 

When downloading these files, there's no sketch file to open - how does one import/sync these assets to use them?

This is what he gets after downloading this:

![image](https://user-images.githubusercontent.com/6905546/78001802-85e49600-7336-11ea-82d9-96c36e198429.png)

I'm not a sketch user - advice would be appreciated

**Comment by saulmases** [comment]
Hi @wernerbarnard 

I abandoned the project as it was not useful anymore. Everything should be found in antd page.
